name: Build

on:
  push:
    branches:
      - main

jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add clippy
          rustup target add wasm32-wasi

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "leaf-wasm-js"

      - name: Build
        run: |
          ./build.sh

      - name: Upload cli binary
        uses: actions/upload-artifact@v3
        with:
          name: quickjs.wasm
          path: quickjs.wasm